services:
  - type: web
    name: pregnancy-tracker-api
    runtime: docker
    plan: free
    rootDir: pregnancy-tracker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: FRONTEND_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false
